name: STAMP Devops Workflow
on:  
  pull_request: 
    branches: [master]
jobs:  
  test:
    runs-on: ubuntu-latest    
    steps:
      - name: Execute STAMP Functional Testing
      - run: curl -X POST 'https://$STP_Host/STAMPApi/Execute/$STP_TestPlan' -H 'ApiToken:$STP_ApiToken'
      - env:
          STP_Host: chp1.cloudstamp.net
          STP_ApiToken: cG9pbnRlbF9hZG1pbjpzbXIwU2l5eEsrY1ZTVHl0TFBuQWxRPT0=
          STP_TestPlan: DEMO_FT
